"""Alert endpoints — monitoring dashboard and on-demand analysis."""

from fastapi import APIRouter, HTTPException, Query
from api.services.monitoring import get_alerts, run_anomaly_scan, acknowledge_alert

router = APIRouter(prefix="/alerts", tags=["Alerts"])


@router.get("")
def list_alerts(
    severity: str | None = Query(None, description="Filter by severity: HIGH, MEDIUM, LOW"),
    anomaly_type: str | None = Query(None, description="Filter by anomaly type"),
    alert_source: str | None = Query(None, description="Filter by source: anomaly, cross_category, emerging_theme, product, data_quality"),
    acknowledged: bool | None = Query(None, description="Filter by acknowledged status"),
    limit: int = Query(50, ge=1, le=200, description="Max alerts to return"),
):
    """Get alerts from the alert log.

    Alerts are generated by the Snowflake Task (scheduled) or on-demand analysis.
    Filter by severity, type, source, or acknowledgement status.
    """
    return get_alerts(severity, anomaly_type, alert_source, acknowledged, limit)


@router.post("/analyze")
def analyze_now():
    """Run a fresh anomaly scan on-demand.

    Returns current anomalies, cross-category patterns, emerging themes,
    product alerts, and data quality status. Does NOT write to the alert log
    (idempotent — safe to call repeatedly during demos).
    """
    return run_anomaly_scan()


@router.patch("/{alert_id}/acknowledge")
def ack_alert(alert_id: str):
    """Mark an alert as acknowledged."""
    success = acknowledge_alert(alert_id)
    if not success:
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found")
    return {"alert_id": alert_id, "acknowledged": True}
