-- Tier 1: Category-level sentiment summary
-- Always statistically valid (14 categories, thousands of reviews each)
-- Primary mart for Cortex Analyst semantic model

{{ config(materialized='table') }}

SELECT
    DERIVED_CATEGORY,
    COUNT(*) AS REVIEW_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(SENTIMENT_SCORE), 4) AS AVG_SENTIMENT,
    ROUND(MEDIAN(SENTIMENT_SCORE), 4) AS MEDIAN_SENTIMENT,
    COUNT(CASE WHEN RATING <= 2 THEN 1 END) AS NEGATIVE_REVIEW_COUNT,
    COUNT(CASE WHEN RATING >= 4 THEN 1 END) AS POSITIVE_REVIEW_COUNT,
    ROUND(COUNT(CASE WHEN RATING <= 2 THEN 1 END)::FLOAT / COUNT(*), 4) AS NEGATIVE_RATE,
    COUNT(CASE WHEN VERIFIED_PURCHASE = TRUE THEN 1 END) AS VERIFIED_COUNT,
    ROUND(AVG(HELPFUL_VOTE), 2) AS AVG_HELPFUL_VOTES
FROM {{ ref('enriched_reviews') }}
WHERE DERIVED_CATEGORY IS NOT NULL
GROUP BY DERIVED_CATEGORY
