USE ROLE TRAINING_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REVIEWSENSE_DB;

-- 1) 看原始表有多少数据
SELECT COUNT(*) AS curated_cnt
FROM CURATED.ELECTRONICS_REVIEWS;

-- 2) 看去重后的视图有多少数据
SELECT COUNT(*) AS dedup_cnt
FROM CURATED.V_ELECTRONICS_REVIEWS_DEDUP;

-- 3) 创建 analytics schema
CREATE SCHEMA IF NOT EXISTS REVIEWSENSE_DB.ANALYTICS;

-- 4) 创建基础视图
CREATE OR REPLACE VIEW REVIEWSENSE_DB.ANALYTICS.V_REVIEWS_GENAI_BASE AS
SELECT
  REVIEW_ID::STRING           AS REVIEW_ID,
  ASIN::STRING                AS ASIN,
  USER_ID::STRING             AS USER_ID,
  RATING::NUMBER              AS RATING,
  TITLE::STRING               AS TITLE,
  REVIEW_TEXT::STRING         AS REVIEW_TEXT,
  VERIFIED_PURCHASE::BOOLEAN  AS VERIFIED_PURCHASE,
  HELPFUL_VOTE::NUMBER        AS HELPFUL_VOTE,
  REVIEW_TS::TIMESTAMP_NTZ    AS REVIEW_TS,
  CATEGORY::STRING            AS CATEGORY
FROM REVIEWSENSE_DB.CURATED.V_ELECTRONICS_REVIEWS_DEDUP;

-- 5) 创建 demo 主表
CREATE OR REPLACE TABLE REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI AS
SELECT
  REVIEW_ID,
  ASIN,
  USER_ID,
  RATING,
  TITLE,
  REVIEW_TEXT,
  VERIFIED_PURCHASE,
  HELPFUL_VOTE,
  REVIEW_TS,
  CATEGORY,
  LENGTH(TRIM(REVIEW_TEXT)) AS TEXT_LEN
FROM REVIEWSENSE_DB.ANALYTICS.V_REVIEWS_GENAI_BASE
WHERE REVIEW_TEXT IS NOT NULL
  AND LENGTH(TRIM(REVIEW_TEXT)) >= 20
  AND RATING BETWEEN 1 AND 5
  AND REVIEW_TS IS NOT NULL;

-- 6) 检查主表行数
SELECT COUNT(*) AS genai_ready_cnt
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI;

-- 7) 随便看几行数据
SELECT *
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI
LIMIT 10;


SELECT ASIN,
       COUNT(*) AS total_reviews,
       ROUND(AVG(RATING), 2) AS avg_rating
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI
GROUP BY ASIN
HAVING COUNT(*) >= 20
ORDER BY total_reviews DESC
LIMIT 20;