USE ROLE TRAINING_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REVIEWSENSE_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE REVIEWSENSE_DB.ANALYTICS.REVIEWS_SENTIMENT AS
SELECT
    REVIEW_ID,
    ASIN,
    USER_ID,
    RATING,
    TITLE,
    REVIEW_TEXT,
    VERIFIED_PURCHASE,
    HELPFUL_VOTE,
    REVIEW_TS,
    CATEGORY,
    TEXT_LEN,
    CASE
        WHEN RATING >= 4 THEN 'Positive'
        WHEN RATING = 3 THEN 'Neutral'
        ELSE 'Negative'
    END AS SENTIMENT_LABEL
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI;

SELECT COUNT(*) AS sentiment_rows
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_SENTIMENT;

SELECT *
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_SENTIMENT
LIMIT 10;


SELECT
    ASIN,
    COUNT(*) AS total_reviews,
    ROUND(AVG(RATING), 2) AS avg_rating,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN 1 ELSE 0 END) AS positive_reviews,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN 1 ELSE 0 END) AS neutral_reviews,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN 1 ELSE 0 END) AS negative_reviews,
    ROUND(100.0 * SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN 1 ELSE 0 END) / COUNT(*), 2) AS positive_pct,
    ROUND(100.0 * SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN 1 ELSE 0 END) / COUNT(*), 2) AS negative_pct
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_SENTIMENT
GROUP BY ASIN
HAVING COUNT(*) >= 20
ORDER BY negative_pct DESC, total_reviews DESC
LIMIT 20;