USE ROLE TRAINING_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REVIEWSENSE_DB;
USE SCHEMA ANALYTICS;

SELECT
    ASIN,
    COUNT(*) AS total_reviews,
    ROUND(AVG(RATING), 2) AS avg_rating,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN 1 ELSE 0 END) AS positive_reviews,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN 1 ELSE 0 END) AS neutral_reviews,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN 1 ELSE 0 END) AS negative_reviews,
    ROUND(100.0 * SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN 1 ELSE 0 END) / COUNT(*), 2) AS positive_pct,
    ROUND(100.0 * SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN 1 ELSE 0 END) / COUNT(*), 2) AS negative_pct
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_SENTIMENT
WHERE ASIN = 'B01G8JO5F2'
GROUP BY ASIN;


SELECT
    REVIEW_ID,
    RATING,
    TITLE,
    REVIEW_TEXT,
    HELPFUL_VOTE,
    REVIEW_TS
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_SENTIMENT
WHERE ASIN = 'B01G8JO5F2'
  AND SENTIMENT_LABEL = 'Negative'
ORDER BY HELPFUL_VOTE DESC NULLS LAST, REVIEW_TS DESC
LIMIT 15;


SELECT
    REVIEW_ID,
    RATING,
    TITLE,
    REVIEW_TEXT,
    HELPFUL_VOTE,
    REVIEW_TS
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_SENTIMENT
WHERE ASIN = 'B01G8JO5F2'
  AND SENTIMENT_LABEL = 'Positive'
ORDER BY HELPFUL_VOTE DESC NULLS LAST, REVIEW_TS DESC
LIMIT 15;